services:
  config1:
    build: .
    container_name: config1
    environment:
      - SERVER_PORT=8888
    ports:
      - "8888:8888"
    networks:
      - dist-sys-ms-network

  config2:
    build: .
    container_name: config2
    environment:
      - SERVER_PORT=8889
    ports:
      - "8889:8889"
    networks:
      - dist-sys-ms-network

networks:
  dist-sys-ms-network:
    external: true
