spring:
    application:
        name: config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/rarycoringa/dist-sys-ms-config-files.git
                    clone-on-start: true
                    default-label: main

server:
    port: ${SERVER_PORT:8888}

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
